//! Annotations over an HTML-rendered document.
//!
//! The paged mode annotates a picture of a document: it walks rendered frames
//! for geometry, hit-tests boxes, and positions marks in page coordinates. HTML
//! has none of that and needs none of it. Every element that Typst emits knows
//! the span it came from, so the document itself can say where each piece of it
//! lives in the source, and the browser can do the rest with ordinary DOM
//! geometry.
//!
//! Kept apart from `annotations.rs` on purpose. The two modes share the sidecar
//! format and the anchor labels — the things that are about annotations — and
//! nothing about how a document is drawn.

use std::sync::Arc;

use serde::Serialize;
use tinymist_project::LspCompiledArtifact;
use tinymist_std::typst::TypstDocument;
use typst::World;
use typst::syntax::{FileId, Source, Span};
use typst_html::{HtmlElement, HtmlNode};

use super::annotations::{
    AnnotationRecord, Scope, dev_asset, doc_file, find_anchors, read_sidecar, sidecar_path,
};

/// The attribute carrying an element's source range, as `start:end` byte
/// offsets into the file being served.
pub const SRC_ATTR: &str = "data-typst-src";

/// The attribute carrying the range of a run of *text*, which is what
/// annotations actually land on. It sits on the element that holds the run
/// where there is one, so the document's structure is left as the exporter
/// wrote it.
pub const TEXT_ATTR: &str = "data-typst-text";

/// The page that hosts an HTML-mode document: its own shell, its own script,
/// its own stylesheet. It shares nothing with the paged frontend.
pub fn shell_html() -> String {
    dev_asset("html_annotations.html", include_str!("html_annotations.html"))
}

/// The HTML-mode client script, read from the source tree when there is one so
/// it can be edited without rebuilding.
pub fn client_js() -> String {
    dev_asset("html_annotations.js", include_str!("html_annotations.js"))
}

/// The HTML-mode stylesheet.
pub fn client_css() -> String {
    dev_asset("html_annotations.css", include_str!("html_annotations.css"))
}

/// The export shims: show rules that recover what Typst's HTML export drops.
/// Read from the source tree when there is one, so they can be edited live.
pub fn shims_typ() -> String {
    dev_asset("html_shims.typ", include_str!("html_shims.typ"))
}

/// The source-tree path of the shims, for watching.
pub fn shims_path() -> std::path::PathBuf {
    std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("src/tool/preview/html_shims.typ")
}

/// The generated file that is compiled in the document's place: the shims,
/// then the document itself. Show rules apply to what follows them, and an
/// include splices the document in after, so the rules cover all of it.
pub fn wrapper_source(main_name: &str) -> String {
    let quoted = main_name.replace('\\', "\\\\").replace('"', "\\\"");
    format!(
        "// Generated by talimist to install HTML export shims. Not written to disk.\n\
         {}\n#include \"{quoted}\"\n",
        shims_typ()
    )
}

/// Where a document's wrapper lives: beside it, so the document's own relative
/// imports and its sidecar are unaffected.
fn wrapper_vpath(main: FileId) -> Option<typst::syntax::VirtualPath> {
    let path = main.vpath().get_with_slash();
    let (dir, name) = path.rsplit_once('/')?;
    typst::syntax::VirtualPath::new(format!("{dir}/.talimist-html.{name}")).ok()
}

/// Compiles the document through a wrapper that installs the shims.
///
/// The document stops being the compile's main file, so annotations are told
/// where it went; everything else — the sidecar, the anchors, the edits —
/// keeps pointing at the real file.
pub fn install_shims(verse: &mut tinymist_project::LspUniverse) -> Result<ShimEntry, String> {
    use reflexo_typst::{Bytes, ShadowApi};
    use tinymist_project::{EntryManager, EntryReader, EntryState};

    let entry = verse.entry_state();
    let root = entry.root().ok_or("the compile has no root")?;
    let main = entry.main().ok_or("the compile has no main file")?;
    let name = main
        .vpath()
        .file_name()
        .ok_or("the main file has no name")?
        .to_owned();
    let vpath = wrapper_vpath(main).ok_or("cannot place the shim wrapper")?;
    let wrapper_entry = EntryState::new_rooted(root.clone(), Some(vpath.clone()));
    wrapper_entry
        .main()
        .ok_or("cannot resolve the shim wrapper")?;

    let path = vpath
        .realize(&root)
        .map_err(|err| format!("cannot resolve the wrapper path: {err}"))?;
    let source = wrapper_source(&name);
    // Shadowed by path, not by id: a shadow set by id wins over every later
    // one set by path, and the wrapper is rewritten by path whenever the shims
    // are edited.
    verse
        .map_shadow(&path, Bytes::from_string(source))
        .map_err(|err| format!("cannot install the HTML shims: {err}"))?;
    verse
        .mutate_entry(wrapper_entry)
        .map_err(|err| format!("cannot compile through the HTML shims: {err:?}"))?;
    super::annotations::set_doc_file(main);

    Ok(ShimEntry {
        path,
        main_name: name,
    })
}

/// The installed wrapper, so it can be rewritten when the shims change.
#[derive(Debug, Clone)]
pub struct ShimEntry {
    /// Where the wrapper lives, as the compiler addresses it.
    pub path: std::path::PathBuf,
    /// The file name of the document it includes.
    pub main_name: String,
}

/// The source-tree paths of the HTML-mode assets, for dev asset watching.
pub fn asset_paths() -> Vec<std::path::PathBuf> {
    let dir = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("src/tool/preview");
    [
        "html_annotations.html",
        "html_annotations.js",
        "html_annotations.css",
        "html_shims.typ",
    ]
    .iter()
    .map(|name| dir.join(name))
    .collect()
}

/// One annotation, as the HTML client needs it: everything the sidecar holds,
/// plus where its anchors sit in the source. The client finds the element that
/// covers that offset; the server does not need to know how it is drawn.
#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct HtmlPin {
    /// The annotation kind.
    #[serde(rename = "type")]
    pub rtype: String,
    /// The unique id.
    pub uuid: String,
    /// The display letter.
    pub letter: String,
    /// The author.
    pub author: String,
    /// The message.
    pub content: String,
    /// Creation time, ISO 8601 UTC.
    pub time: String,
    /// The status.
    pub status: String,
    /// The discussion thread.
    pub discussion: Vec<super::annotations::AnnotationReply>,
    /// What the annotation refers to.
    pub scope: String,
    /// The byte offset of the anchor in the source.
    pub start: usize,
    /// The byte offset the annotation reaches to: the end anchor of a span, or
    /// the start again for everything else.
    pub end: usize,
}

/// The document as HTML, with every element labelled with its source range.
pub fn html_document(art: &LspCompiledArtifact) -> Result<String, String> {
    let Some(doc) = art.success_doc() else {
        return Err("no document".into());
    };
    let TypstDocument::Html(doc) = &doc else {
        return Err("this document is not compiled for HTML; run with --format html".into());
    };
    let world = art.world();
    // The document, not the compile's main file: with the shims installed
    // those differ, and what is labelled is what the reader is looking at.
    let main = doc_file(world);
    let source = world
        .source(main)
        .map_err(|err| format!("cannot read the document's source: {err}"))?;

    // Labelled in place on a copy: the document's parts are private, and its
    // introspector is not derived from the output, so it cannot be rebuilt from
    // pieces.
    let mut labelled = (**doc).clone();
    label_element(labelled.root_mut(), &source, main);
    typst_html::html(&labelled, &typst_html::HtmlOptions::default())
        .map_err(|err| format!("cannot encode the document as HTML: {err:?}"))
}

/// The document as the client wants it: its title, and the contents of its
/// body. The shell owns the page — its head, its overlay, its script — so the
/// document arrives as something to put inside, not as a page of its own.
#[derive(Debug, Clone, Serialize)]
pub struct HtmlFragment {
    /// The document's title, if it declared one.
    pub title: String,
    /// Everything between `<body>` and `</body>`.
    pub body: String,
}

/// Splits a rendered document into the parts the shell needs.
pub fn fragment(html: &str) -> HtmlFragment {
    let between = |open_tag: &str, close: &str| -> Option<String> {
        let open = html.find(open_tag)?;
        let start = html[open..].find('>')? + open + 1;
        let end = html[start..].find(close)? + start;
        Some(html[start..end].to_owned())
    };
    HtmlFragment {
        title: between("<title", "</title>").unwrap_or_default(),
        body: between("<body", "</body>").unwrap_or_else(|| html.to_owned()),
    }
}

/// Labels an element, and everything inside it, with the source range it came
/// from.
fn label_element(element: &mut HtmlElement, source: &Source, main: FileId) {
    label_within(element, source, main, false)
}

/// `in_math` says whether this element is inside a `<math>`, where the
/// children of an element are characters rather than markup: a `<span>` under
/// an `<mi>` is not math to a browser, and the equation renders as body text.
/// Elements there still carry their range; only text is left alone, so an
/// equation is one atom to annotate rather than a run of words.
fn label_within(element: &mut HtmlElement, source: &Source, main: FileId, in_math: bool) {
    if let Some(range) = span_range(element.span, source, main) {
        if let Ok(attr) = typst_html::HtmlAttr::intern(SRC_ATTR) {
            element
                .attrs
                .push(attr, format!("{}:{}", range.start, range.end));
        }
    }
    let in_math = in_math || element.tag.resolve().as_str() == "math";
    let opaque = matches!(
        element.tag.resolve().as_str(),
        "head" | "title" | "script" | "style"
    );
    if opaque {
        return;
    }

    // An element holding nothing but one run of text can say where that run
    // came from itself; a wrapper would only be somewhere to hang an attribute
    // that already has a home. This is not merely tidier: inside MathML the
    // children of an element are characters, and a `<span>` among them stops
    // the browser reading it as math.
    if element.children.len() == 1 {
        if let HtmlNode::Text(_, span) = &element.children[0] {
            if let Some(range) = span_range(*span, source, main) {
                if let Ok(attr) = typst_html::HtmlAttr::intern(TEXT_ATTR) {
                    element
                        .attrs
                        .push(attr, format!("{}:{}", range.start, range.end));
                }
            }
            return;
        }
    }

    for child in element.children.make_mut() {
        match child {
            HtmlNode::Element(child) => label_within(child, source, main, in_math),
            // A run with siblings has nowhere of its own to keep its range, so
            // it gets a wrapper — except in math, where the structure is the
            // meaning and the equation is left whole.
            HtmlNode::Text(text, span) if !in_math => {
                let Some(range) = span_range(*span, source, main) else {
                    continue;
                };
                let (Ok(tag), Ok(attr)) = (
                    typst_html::HtmlTag::intern("span"),
                    typst_html::HtmlAttr::intern(TEXT_ATTR),
                ) else {
                    continue;
                };
                let inner = HtmlNode::Text(text.clone(), *span);
                *child = HtmlNode::Element(
                    HtmlElement::new(tag)
                        .with_attr(attr, format!("{}:{}", range.start, range.end))
                        .with_children(std::iter::once(inner).collect())
                        .spanned(*span),
                );
            }
            _ => {}
        }
    }
}

/// The byte range a span covers in the file being served, if it is from there.
fn span_range(span: Span, source: &Source, main: FileId) -> Option<std::ops::Range<usize>> {
    if span.id()? != main {
        return None;
    }
    typst_shim::syntax::source_range(source, span)
}

/// Every annotation with the source offsets of its anchors.
pub fn html_pins(art: &LspCompiledArtifact) -> Vec<HtmlPin> {
    let Some(sidecar) = sidecar_path(art) else {
        return vec![];
    };
    let (records, _) = read_sidecar(&sidecar);
    if records.is_empty() {
        return vec![];
    }
    let world = art.world();
    let Ok(source) = world.source(doc_file(world)) else {
        return vec![];
    };
    let text = source.text();

    records
        .iter()
        .filter_map(|rec| pin_for(rec, text))
        .collect()
}

fn pin_for(rec: &AnnotationRecord, text: &str) -> Option<HtmlPin> {
    let anchors = find_anchors(text, &rec.uuid);
    let (start, scope, label) = anchors.first().cloned()?;
    let end = match scope {
        Scope::Span => anchors
            .iter()
            .rev()
            .find(|(off, _, l)| *off > start && l.ends_with(".end>"))
            .map(|(off, _, _)| *off)
            .unwrap_or(start + label.len()),
        _ => start,
    };
    Some(HtmlPin {
        rtype: rec.rtype.clone(),
        uuid: rec.uuid.clone(),
        letter: rec.letter.clone(),
        author: rec.author.clone(),
        content: rec.content.clone(),
        time: rec.time.clone(),
        status: rec.status.clone(),
        discussion: rec.discussion.clone(),
        scope: scope.as_str().into(),
        start,
        end,
    })
}

/// What an HTML-mode server can answer.
pub trait HtmlAnnotationServer: Send + Sync {
    /// The document as HTML, labelled with source ranges.
    fn document(&self) -> Result<String, String>;
    /// Every annotation, with the source offsets of its anchors.
    fn pins(&self) -> Vec<HtmlPin>;
}

/// Holds the last compiled artifact, so both answers come from one document.
pub struct ArtifactHtmlServer {
    /// The most recent successful compile.
    pub last_art: Arc<parking_lot::Mutex<Option<LspCompiledArtifact>>>,
}

impl HtmlAnnotationServer for ArtifactHtmlServer {
    fn document(&self) -> Result<String, String> {
        let art = self.last_art.lock().clone().ok_or("nothing compiled yet")?;
        html_document(&art)
    }

    fn pins(&self) -> Vec<HtmlPin> {
        let Some(art) = self.last_art.lock().clone() else {
            return vec![];
        };
        html_pins(&art)
    }
}
